version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  receiver-service:
    build: ./Receiver-Service
    ports:
      - '4000:3000'
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/Receiver
    depends_on:
      - mongodb
      - redis

  listener-service:
    build: ./Listener-Service
    ports:
      - '6000:5000'
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/Receiver
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data: